### ISSUE TITLE
Homework 7 Fixes

### ISSUE THREAD

**Issue by rtrana** [mbujnows1586/vacation-Able1#2]
Marcel, in order to get credit back on your homework score, fixes need to be completed by Thursday, March 25th at 9:00 p.m. (as part of the Homework 8 deadline) and should be pushed to GitHub. Once you complete all the fixes listed below, close this issue. Closing this issue will notify me - no need to resubmit to D2L. Please note that these fixes are needed for your final project, but you can only earn credit back on the assignment score if the fixes are submitted by the date/time listed above.

**Part II**: 0.10/0.25
- [ ] Your current domain model is a "User" type - i.e. someone who will be signing in to your application. You need to change this to something else that will be represented in your code - for example, a Review (as you intend on having your users be able to review vacation spots for accessibility).

**Part III**: 0.10/0.10

**Part IV**: 0.25/0.25
- [ ] While you did modify this, it needs to work with a different domain type.

**Part V**: 0/0.25 - Not complete

**Part VI**: 0/0.15 - Not complete

**Current Score:** 0.45/1.0

**Comment by mbujnows1586** [comment]
hi professor, i updated the changes
